version: '3.9'
services:
  db:
    image: mysql
    container_name: db
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    env_file: .env
    restart: always
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fendou
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    ports:
      - '33061:3306'
    networks:
      - app-network
    security_opt:
      - seccomp:unconfined
  node3:
    build: .
    image: node
    container_name: node3
    restart: always 
    volumes:
      - .:/usr/node/app/
    environment:
      - DB_HOST=db
    ports:
      - 4000:3000
    depends_on: 
      - db
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    name: kkk-project
    driver: bridge