version: '3.9'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql-dump:/docker-entrypoint-initdb.d
    env_file: .env
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '33061:3306'
    networks:
      - app-network
    security_opt:
      - seccomp:unconfined
  node-end:
    build: .
    image: node
    container_name: node-end
    restart: always
    volumes:
      - .:/usr/node
    environment:
      - DB_HOST=db
    ports:
      - 4000:3000
    depends_on:
      - db
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge
